### ISSUE TITLE
Networking Probeprojekt

### ISSUE THREAD

**Issue by ChibiChanXYZ** [mehoba/Munchkin#8]
Als Team wollen wir, dass Krio net ausprobiert wird, um zu entscheiden, ob dieses im weiteren Verlauf des Projekts zum Networking geeignet ist.

Networking wurde Krio net vorgeschlagen
Hierfür wurde beschlossen zuerst Krio net zu testen und ein Probeprojekt zu erstellen

Es sollte eine Entscheidung gefällt werden, ob Krio net für Networking im Programm geeignet ist

**Comment by FreezyCGI** [comment]
**Aufgetretene Probleme:**
- Importieren von Kryo.Net
- Maven?????
- Erstellen von Server und Client (Wo welche Klasse erstellen bzw. neues Projekt?)
- **Starten von einem Emulator**
- Networking darf nur in einem Thread gemacht werden

**Folgende fragen sollten beantwortet werden, bevor fortgesetzt wird:**
1.
Server Code im gleichen Projekt oder lieber ein neues anlegen?
Wenn im gleichen: Wie macht man einen Client/Server build bzw. wie führt man beides getrennt aus?
Wenn neues Projekt: Wie synchronisiert man am besten die Klassen, welche in beiden Projekte verwendet werden.

2.
Wann werden Server zur Verfügung gestellt?
Details zu den Servern: Zugriff? Betriebssystem?

**Comment by FreezyCGI** [comment]
Starten von 2 Emulatoren funktioniert (Client und Server).
Die Kommunikation zwischen beiden funktioniert aber nicht nicht.

**Comment by FreezyCGI** [comment]
Kommunikation zwischen einem Server (echtes Smartphone) und mehreren Clients(Emulator).
Clients werden als Spieler abgespeichert mittels Name und id.
